---
  - src: git@github.com:Andrey-netology/filebeat_role.git
    scm: git
    version: "main"
    name: filebeat

  - src: git@github.com:Andrey-netology/kibana-role.git
    scm: git
    version: "main"
    name: kibana
